"""empty message

Revision ID: 06d9d3152bd3
Revises: 667d29a64eaf
Create Date: 2026-03-03 15:20:46.590436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d9d3152bd3'
down_revision = '667d29a64eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_children', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('pricing_type')

    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('num_children')

    with op.batch_alter_table('apartment_types', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
