"""empty message

Revision ID: 084c6685aa0b
Revises: 2c7c21a81299
Create Date: 2026-04-30 17:56:42.770643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084c6685aa0b'
down_revision = '2c7c21a81299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('original_check_out', sa.DateTime(), nullable=False),
    sa.Column('new_check_out', sa.DateTime(), nullable=False),
    sa.Column('extra_nights', sa.Integer(), nullable=False),
    sa.Column('extra_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_extensions')
    # ### end Alembic commands ###
