"""Added updated_at to Unit

Revision ID: 667d29a64eaf
Revises: 6d948b8d32ff
Create Date: 2026-03-03 10:46:50.628613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667d29a64eaf'
down_revision = '6d948b8d32ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
