"""Add id_upload_url to Booking

Revision ID: 6ce738cda75e
Revises: b43d7502e1ba
Create Date: 2026-03-23 18:17:09.121561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce738cda75e'
down_revision = 'b43d7502e1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_upload_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('id_upload_url')

    # ### end Alembic commands ###
