"""Added unit_id foreign key to ServiceRequest

Revision ID: 6d948b8d32ff
Revises: 
Create Date: 2026-03-03 10:38:47.840523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d948b8d32ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_service_requests_unit', 'units', ['unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###
