"""Added_payment_ref_paid_paid_at_fields_to_ServiceRequest

Revision ID: 735c88b1bf1e
Revises: eef150e1a4f9
Create Date: 2026-04-13 15:29:58.797876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735c88b1bf1e'
down_revision = 'eef150e1a4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('paid')
        batch_op.drop_column('payment_reference')

    # ### end Alembic commands ###
