"""Add BookingExtension model

Revision ID: 738d8829aacb
Revises: 084c6685aa0b
Create Date: 2026-04-30 18:39:00.204199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738d8829aacb'
down_revision = '084c6685aa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_extensions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_extensions_payment_id', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_extensions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_extensions_payment_id', type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
