"""add expires_at to bookings

Revision ID: 824bc3435a0a
Revises: 06d9d3152bd3
Create Date: 2026-03-04 10:57:41.517616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824bc3435a0a'
down_revision = '06d9d3152bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
