"""updated_payment_model

Revision ID: 97fb8e4861c0
Revises: 735c88b1bf1e
Create Date: 2026-04-16 14:08:35.496696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fb8e4861c0'
down_revision = '735c88b1bf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_payments_payment_reference'))
        batch_op.create_unique_constraint('fk_payments_service_request_id', ['payment_reference'])
        batch_op.drop_constraint('fk_payments_service_request_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_service_request_id', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_payments_payment_reference'), ['payment_reference'], unique=1)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
