"""added_verified_ids_model

Revision ID: eef150e1a4f9
Revises: 6ce738cda75e
Create Date: 2026-03-26 17:54:44.385639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef150e1a4f9'
down_revision = '6ce738cda75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('verification_id', sa.String(length=100), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('selfie_url', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verified_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_ids_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_ids_email'))

    op.drop_table('verified_ids')
    # ### end Alembic commands ###
